name: Frontend test
on:
  - push
  - pull_request
jobs:
  Frontend-Test:
    name: Frontend test
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install npm
        run: npm install
      - name: Run test
        run: npm test
